export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
const shop = searchParams.get("shop");

if (!shop) {
  return new Response("Missing shop", { status: 400 });
}

  // 🔴 AICI pui token-ul din terminal
  const accessToken = "shpua_914cc7574f8543b551af28cad10b2d28";

  const res = await fetch(`https://${shop}/admin/api/2024-01/products.json`, {
    method: "POST",
    headers: {
      "X-Shopify-Access-Token": accessToken,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      product: {
        title: "Test product Selliora",
        body_html: "<strong>Generated by AI</strong>",
        vendor: "Selliora",
        product_type: "AI Product",
      },
    }),
  });

  const data = await res.json();

  return Response.json(data);
}