export async function GET() {
  const shop = "selliora-test.myshopify.com";

  // 🔴 AICI pui token-ul din terminal
  const accessToken = "shpua_914cc7574f8543b551af28cad10b2d28";

  const res = await fetch(`https://${shop}/admin/api/2024-01/products.json`, {
    method: "POST",
    headers: {
      "X-Shopify-Access-Token": accessToken,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      product: {
        title: "Test product Selliora",
        body_html: "<strong>Generated by AI</strong>",
        vendor: "Selliora",
        product_type: "AI Product",
      },
    }),
  });

  const data = await res.json();

  return Response.json(data);
}